# Generated by Django 6.1.1 on 2026-09-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.FloatField()),
                ('cashout_target', models.FloatField()),
                ('crash_multiplier', models.FloatField()),
                ('won', models.BooleanField(db_index=True)),
                ('profit_loss', models.FloatField()),
                ('balance_after', models.FloatField()),
                ('site', models.CharField(default='ilotbet', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Bet & Stake Ledger',
                'verbose_name_plural': 'Bet & Stake Ledgers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_stake', models.FloatField(default=50.0, help_text='Starting stake amount in NGN')),
                ('strategy', models.CharField(default='martingale', help_text='martingale, dalembert, flat, fibonacci', max_length=50)),
                ('multiplier', models.FloatField(default=3.0, help_text='Loss escalation multiplier (e.g. 3.0 for 1.50x cashout)')),
                ('auto_cashout', models.FloatField(default=1.5, help_text='Target cashout multiplier (e.g. 1.50x)')),
                ('max_stake', models.FloatField(default=5000.0, help_text='Safety maximum stake in NGN')),
                ('max_loss_steps', models.IntegerField(default=5, help_text='Maximum consecutive losing streak steps')),
                ('stop_loss', models.FloatField(default=10000.0, help_text='Total session stop-loss in NGN')),
                ('profit_target', models.FloatField(default=5000.0, help_text='Total session profit target in NGN')),
                ('dry_run', models.BooleanField(default=False, help_text='Simulation mode without placing real bets')),
                ('site', models.CharField(default='ilotbet', max_length=50)),
                ('game_url', models.TextField(default='https://www.ilotbet.com/pc/iframe')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Configuration',
                'verbose_name_plural': 'Bot Configurations',
            },
        ),
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Bot Log',
                'verbose_name_plural': 'Bot Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField(db_index=True)),
                ('site', models.CharField(db_index=True, default='ilotbet', max_length=50)),
                ('phase', models.CharField(default='FINISHED', max_length=50)),
                ('is_under_2x', models.BooleanField(db_index=True, default=False)),
                ('is_over_10x', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Extracted Crash Multiplier',
                'verbose_name_plural': 'Extracted Crash Multipliers',
                'ordering': ['-timestamp'],
            },
        ),
    ]
