# Generated by Django 6.1.1 on 2026-09-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='game_url',
            field=models.TextField(default='https://www.ilotbet.com/pc/iframe', help_text='Encrypted at rest: session URL'),
        ),
    ]
