# Generated by Django 6.1.1 on 2026-09-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0002_alter_botconfig_game_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='network_auto_retry',
            field=models.BooleanField(default=True, help_text='Automatically retry on connection loss'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='network_max_retries',
            field=models.IntegerField(default=5, help_text='Maximum consecutive reconnect attempts'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='network_retry_delay',
            field=models.IntegerField(default=10, help_text='Seconds to wait between retry attempts'),
        ),
    ]
