# Generated by Django 6.1.1 on 2026-09-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0003_botconfig_network_auto_retry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betrecord',
            name='game',
            field=models.CharField(db_index=True, default='aviator', max_length=50),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='ai_autonomous_mode',
            field=models.BooleanField(default=False, help_text='Allow AI to dynamically adjust target odds or pause staking'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='Enable AI LLM Advisor & Market Intelligence'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='ai_model',
            field=models.CharField(blank=True, default='gemini-2.0-flash', help_text='Model ID dynamically selected from provider', max_length=100),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openrouter', 'OpenRouter.ai')], default='gemini', max_length=50),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='ai_risk_tolerance',
            field=models.CharField(choices=[('conservative', 'Conservative'), ('balanced', 'Balanced'), ('aggressive', 'Aggressive')], default='conservative', help_text='Risk appetite model used for AI staking adjustments', max_length=20),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='game',
            field=models.CharField(default='aviator', help_text='Active game type (aviator, crash, limbo)', max_length=50),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='gemini_api_key',
            field=models.TextField(blank=True, default='', help_text='Encrypted Google AI Studio API Key'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='openrouter_api_key',
            field=models.TextField(blank=True, default='', help_text='Encrypted OpenRouter API Key'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='platform',
            field=models.CharField(default='ilotbet', help_text='Active platform addon (ilotbet, bcgame, sportybet)', max_length=50),
        ),
        migrations.AddField(
            model_name='extractedodds',
            name='game',
            field=models.CharField(db_index=True, default='aviator', max_length=50),
        ),
        migrations.AlterField(
            model_name='betrecord',
            name='site',
            field=models.CharField(db_index=True, default='ilotbet', max_length=50),
        ),
    ]
