# Generated by Django 6.1.1 on 2026-09-12 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0004_betrecord_game_botconfig_ai_autonomous_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('platform', models.CharField(default='ilotbet', max_length=50)),
                ('game', models.CharField(default='best_aviator', max_length=50)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'AI Chat Session',
                'verbose_name_plural': 'AI Chat Sessions',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='game',
            field=models.CharField(default='best_aviator', help_text='Active game type (best_aviator, crash, limbo)', max_length=50),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='game_url',
            field=models.TextField(blank=True, default='https://www.ilotbet.com/pc/iframe', help_text='Encrypted at rest: session URL'),
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System Directive'), ('agent', 'Swarm Agent')], default='user', max_length=20)),
                ('sender_name', models.CharField(default='User', max_length=50)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bot_engine.aichatsession')),
            ],
            options={
                'verbose_name': 'AI Chat Message',
                'verbose_name_plural': 'AI Chat Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
