# Generated by Django 5.2.17 on 2026-09-13 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0005_aichatsession_alter_botconfig_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiscoveryMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('STREAK_TIMING', 'Streak Timing & Hour Analysis'), ('CLUSTER_PATTERN', 'Cluster & Loss Pattern'), ('STRATEGY_RULE', 'Staking & Cashout Rule'), ('RISK_LIMIT', 'Risk & Drawdown Barrier'), ('MARKET_INSIGHT', 'Market Observation'), ('GENERAL', 'General Discovery')], db_index=True, default='GENERAL', max_length=50)),
                ('content', models.TextField(help_text='Empirical finding, pattern rule, or timing discovery')),
                ('evidence_data', models.JSONField(blank=True, default=dict, help_text='Supporting telemetry metrics (hours, streak length, etc.)')),
                ('platform', models.CharField(db_index=True, default='ilotbet', max_length=50)),
                ('game', models.CharField(db_index=True, default='best_aviator', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Fed into active Swarm reasoning if True')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='bot_engine.aichatsession')),
            ],
            options={
                'verbose_name': 'AI Discovery Memory',
                'verbose_name_plural': 'AI Discovery Memories',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
