# Generated by Django 6.1.1 on 2026-09-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0006_aidiscoverymemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='ceiling_rule',
            field=models.BooleanField(default=True, help_text='Always round fractional stakes up to next whole integer (Ceiling Rule)'),
        ),
    ]
